name = "hugo-theme-console++"
license = "MIT"
licenselink = "https://github.com/berbiche/hugo-theme-console/blob/master/LICENSE"
description = "A minimal, responsive and light theme for Hugo inspired by Linux console."
homepage = "https://github.com/berbiche/hugo-theme-console"
tags = ["blog", "gallery", "portfolio", "console", "terminal", "clean", "personal", "minimal", "monotone", "simple", "technical", "responsive", "mobile", "minimalist", "retro", "animation"]
features = ["disqus", "responsive"]
min_version = "0.69.0"

[author]
    name = "Nicolas Berbiche"
    homepage = "https://github.com/berbiche"
    github = "https://github.com/berbiche"

[original]
    author = "Marcin Mierzejewski"
    homepage = "https://mrmierzejewski.com"
    repo = "https://github.com/mrmierzejewski"
